// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy5VKnqEKgo77HmJaAI0_Z2DRaHY4jLQ4',
    appId: '1:233729315120:web:c02a83c61d8c0f756038f5',
    messagingSenderId: '233729315120',
    projectId: 'spendings-app-2a5af',
    authDomain: 'spendings-app-2a5af.firebaseapp.com',
    storageBucket: 'spendings-app-2a5af.firebasestorage.app',
    measurementId: 'G-769KEQ0NTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5gX2Iuvt6co3K1aqmt1tcNN8PvjpIDps',
    appId: '1:233729315120:android:ff1b92489a4032606038f5',
    messagingSenderId: '233729315120',
    projectId: 'spendings-app-2a5af',
    storageBucket: 'spendings-app-2a5af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlfQuZKEZYwiEyGyJI0099cXOUFL5foSE',
    appId: '1:233729315120:ios:c71178519ed0c6d26038f5',
    messagingSenderId: '233729315120',
    projectId: 'spendings-app-2a5af',
    storageBucket: 'spendings-app-2a5af.firebasestorage.app',
    iosBundleId: 'com.example.spendingsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlfQuZKEZYwiEyGyJI0099cXOUFL5foSE',
    appId: '1:233729315120:ios:c71178519ed0c6d26038f5',
    messagingSenderId: '233729315120',
    projectId: 'spendings-app-2a5af',
    storageBucket: 'spendings-app-2a5af.firebasestorage.app',
    iosBundleId: 'com.example.spendingsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy5VKnqEKgo77HmJaAI0_Z2DRaHY4jLQ4',
    appId: '1:233729315120:web:32bfbcdfa07204996038f5',
    messagingSenderId: '233729315120',
    projectId: 'spendings-app-2a5af',
    authDomain: 'spendings-app-2a5af.firebaseapp.com',
    storageBucket: 'spendings-app-2a5af.firebasestorage.app',
    measurementId: 'G-ESP4FY4HLN',
  );
}
